- 문제: https://school.programmers.co.kr/learn/courses/30/lessons/87694

방법: bfs이용
- 지도 크기를 2배로 늘림 -> 안늘리면 길이 아니여도 1칸 차이가 날 수 있어 경로가 되어버림

In [17]:
import numpy

def solution(rectangle, characterX, characterY, itemX, itemY):
    answer = 0
    graph = [[-1] * 22 for _ in range(22)] 
    
    for r in rectangle:
        x1, y1, x2, y2 = map(lambda x: x * 2, r)
        for i in range(x1, x2 + 1):
            for j in range(y1, y2 + 1):
                if x1 < i < x2 and y1 < j < y2:
                    graph[i][j] = 0 # 내부
                elif graph[i][j] != 0:
                    graph[i][j] = 1 # 테두리
    
    graph = numpy.array(graph)
    for g in graph:
        print(g)
    
    return answer

solution([[1,1,7,4],[3,2,5,5],[4,3,6,9],[2,6,8,8]], 1, 3, 7, 8)

[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[-1 -1  1  1  1  1  1  1  1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[-1 -1  1  0  0  0  0  0  1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[-1 -1  1  0  0  0  0  0  1 -1 -1 -1  1  1  1  1  1 -1 -1 -1 -1 -1]
[-1 -1  1  0  0  0  0  0  1 -1 -1 -1  1  0  0  0  1 -1 -1 -1 -1 -1]
[-1 -1  1  0  0  0  0  0  1  1  1 -1  1  0  0  0  1 -1 -1 -1 -1 -1]
[-1 -1  1  0  0  0  0  0  0  0  1 -1  1  0  0  0  1 -1 -1 -1 -1 -1]
[-1 -1  1  0  0  0  0  0  0  0  1  1  1  0  0  0  1  1  1 -1 -1 -1]
[-1 -1  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1 -1 -1 -1]
[-1 -1  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1 -1 -1 -1]
[-1 -1  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1 -1 -1 -1]
[-1 -1  1  0  0  0  0  0  1  1  1  1  1  0  0  0  1  1  1 -1 -1 -1]
[-1 -1  1  0  0  0  0  0  1 -1 -1 -1  1  0  0  0  1 -1 -1 -1 -1 -1]
[-1 -1  1  1  1  1  1  1  1 -1 -1 -1  1  0  0  0

0

In [25]:
%%time
from collections import deque
import numpy as np

def solution(rectangle, characterX, characterY, itemX, itemY):
    answer = 0
    graph = [[-1] * 22 for _ in range(22)] # 2배 늘린 지도
    
    for r in rectangle:
        x1, y1, x2, y2 = map(lambda x: x * 2, r)
        for i in range(x1, x2 + 1):
            for j in range(y1, y2 + 1):
                if x1 < i < x2 and y1 < j < y2:
                    graph[i][j] = 0
                elif graph[i][j] != 0:
                    graph[i][j] = 1
    
    dx = [-1, 1, 0, 0]
    dy = [0, 0, -1, 1]
    
    queue = deque()
    queue.append([characterX * 2, characterY * 2])
    visited = [[1] * 22 for i in range(22)]
    
    while queue:
        x, y = queue.popleft()
         # 아이템이 있는 장소 도착
        if x == itemX * 2 and y == itemY * 2:
            answer = visited[x][y] // 2
            break
        # 아니라면 네 방향 확인
        for k in range(4):
            nx = x + dx[k]
            ny = y + dy[k]
            # 현재 좌표가 테두리 and 아직 방문하지 않은 곳 => queue에 추가 + visited 최단거리로 갱신
            if graph[nx][ny] == 1 and visited[nx][ny] == 1:
                queue.append([nx, ny])
                visited[nx][ny] = visited[x][y] + 1
    
    np.set_printoptions(threshold=np.inf, linewidth=np.inf) #inf = infinity 
    visited = numpy.array(visited)
    print(visited)
    
    return answer

solution([[1,1,7,4],[3,2,5,5],[4,3,6,9],[2,6,8,8]], 1, 3, 7, 8)

[[ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1]
 [ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1]
 [ 1  1  5  4  3  2  3  2  3  1  1  1  1  1  1  1  1  1  1  1  1  1]
 [ 1  1  6  1  1  1  1  1  4  1  1  1  1  1  1  1  1  1  1  1  1  1]
 [ 1  1  7  1  1  1  1  1  5  1  1  1 17 18 19 20 21  1  1  1  1  1]
 [ 1  1  8  1  1  1  1  1  6  1  1  1 16  1  1  1 22  1  1  1  1  1]
 [ 1  1  9  1  1  1  1  1  7  8  9  1 15  1  1  1 23  1  1  1  1  1]
 [ 1  1 10  1  1  1  1  1  1  1 10  1 14  1  1  1 24  1  1  1  1  1]
 [ 1  1 11  1  1  1  1  1  1  1 11 12 13  1  1  1 25 26 27  1  1  1]
 [ 1  1 12  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 28  1  1  1]
 [ 1  1 13  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 29  1  1  1]
 [ 1  1 14  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 30  1  1  1]
 [ 1  1 15  1  1  1  1  1 25 26 27 28 29  1  1  1 33 32 31  1  1  1]
 [ 1  1 16  1  1  1  1  1 24  1  1  1 30  1  1  1 34  1  1  1  1  1]
 [ 1  1 17 18 19 20 21 22 23  1  1

17

In [26]:
%%time
from collections import deque

def solution(rectangle, characterX, characterY, itemX, itemY):
    answer = 0
    graph = [[-1] * 102 for _ in range(102)] # 2배 늘린 지도
    
    for r in rectangle:
        x1, y1, x2, y2 = map(lambda x: x * 2, r)
        for i in range(x1, x2 + 1):
            for j in range(y1, y2 + 1):
                if x1 < i < x2 and y1 < j < y2:
                    graph[i][j] = 0
                elif graph[i][j] != 0:
                    graph[i][j] = 1
    
    dx = [-1, 1, 0, 0]
    dy = [0, 0, -1, 1]
    
    queue = deque()
    queue.append([characterX * 2, characterY * 2])
    visited = [[1] * 102 for i in range(102)]
    
    while queue:
        x, y = queue.popleft()
         # 아이템이 있는 장소 도착
        if x == itemX * 2 and y == itemY * 2:
            answer = visited[x][y] // 2
            break
        # 아니라면 네 방향 확인
        for k in range(4):
            nx = x + dx[k]
            ny = y + dy[k]
            # 현재 좌표가 테두리 and 아직 방문하지 않은 곳 => queue에 추가 + visited 최단거리로 갱신
            if graph[nx][ny] == 1 and visited[nx][ny] == 1:
                queue.append([nx, ny])
                visited[nx][ny] = visited[x][y] + 1
    
    return answer

solution([[1,1,7,4],[3,2,5,5],[4,3,6,9],[2,6,8,8]], 1, 3, 7, 8)

CPU times: user 488 µs, sys: 1 µs, total: 489 µs
Wall time: 494 µs


17